### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by mac-linux-free** [sneakyx/egroupwareserver_extended#1]
Hello Sneaky,

thank you for your great work. Exactly what I was searching for.
Is there a posibility to integrate SSL (selfsigned or letsencrypt)?

Thank you in advance.
Greetings from Stuttgart

**Comment by mac-linux-free** [comment]
nobody here?

**Comment by sneakyx** [comment]
Sorry, I didn't get messages to my mailbox.
Well, I use my own apache-gateway container to connect to different egroupware machines.
But maybe you can use kubernetes.
